-- Auto-generated by matugen from the current wallpaper.
-- Sets Hyprland window border colors. Sourced by hyprland.lua via dofile.
local c = {
    primary          = "#ffb0d0",
    primary_container = "#6e334f",
    muted            = "#d4c2c7",
}

local function hx(s)
    return (s:gsub("^#", ""))
end

hl.config({
    general = {
        col = {
            -- Solid accent border (single color). Force 8-digit hex (matugen .hex is
            -- sometimes 6-digit; rgba() needs 8) so Hyprland accepts it.
            active_border   = "rgba(" .. hx(c.primary):sub(1, 6) .. "ff)",
            inactive_border = "rgba(" .. hx(c.muted):sub(1, 6) .. "aa)",
        },
    },
})
