#!/usr/bin/env bash
# Auto-generated by matugen from the current wallpaper.
# Applies Hyprland window border colors live (no restart needed).
# Source: ~/.config/matugen/templates/matugen-colors.sh

PRIMARY="#ffb596"
PRIMARY_CONTAINER="#71361a"
MUTED="#d8c2ba"

# strip leading '#'
PRIMARY=${PRIMARY#\#}
PRIMARY_CONTAINER=${PRIMARY_CONTAINER#\#}
MUTED=${MUTED#\#}

# active border: gradient foam -> iris
hyprctl keyword general:col.active_border "rgba(${PRIMARY}) rgba(${PRIMARY_CONTAINER}) 45" 2>/dev/null
# inactive border: dimmed muted tone
hyprctl keyword general:col.inactive_border "rgba(${MUTED}aa)" 2>/dev/null
