-- Auto-generated by matugen from the current wallpaper.
-- Sets Hyprland window border colors. Sourced by hyprland.lua via dofile.
local c = {
    primary          = "{{ colors.primary.default.hex }}",
    primary_container = "{{ colors.primary_container.default.hex }}",
    muted            = "{{ colors.on_surface_variant.default.hex }}",
}

local function hx(s)
    return (s:gsub("^#", ""))
end

hl.config({
    general = {
        col = {
            active_border   = { colors = { "rgba(" .. hx(c.primary) .. ")", "rgba(" .. hx(c.primary_container) .. ")" }, angle = 45 },
            inactive_border = "rgba(" .. hx(c.muted):sub(1, 6) .. "aa)",
        },
    },
})
